### ISSUE TITLE
Install in subfolder

### ISSUE THREAD

**Issue by th3b00** [unosquare/passcore#29] opened 2016-08-16 20:49 UTC
Hello.
Installation with README went ok and app is working as main app. But I need it to integrate it with my current app working with one ssl cert. After adding app as subfolder I get only:

```
PassCore logo
Powered by PassCore v2.0.2.beta.2 - OSS and MIT Licensed
Copyright © 2016 Unosquare
```

Is it possible to install app as subfolder of default site?

**Comment by mariodivece** [comment] 2016-08-22 13:34
Duplicate of #30

**Comment by geoperez** [comment] 2018-03-05 14:50
Check the latest version.

**Closed by geoperez** 2018-03-05 14:50 UTC
Labels: duplicate
