### ISSUE TITLE
when someone tries to use a password that was previously used

### ISSUE THREAD

**Issue by saxknicks** [unosquare/passcore#41] opened 2016-09-16 17:55 UTC
So we stop people from using their last two passwords, and when someone does try to use their a previous password, instead of telling them its not allowed due to the policy, it says this " There was an error changing your password
Error Information: The system cannot contact a domain controller to service the authentication request. Please try again later. (Exception from HRESULT: 0x800704F1)"

Is there anyway to change that error message to reflect the true nature of what the issue is?  Otherwise, the product works as expected.

Thanks!

**Comment by roaima** [comment] 2016-09-19 13:44
Possible duplicate of #38

**Comment by mariodivece** [comment] 2017-12-12 01:21
Password policy is not controlled by PassCore.

**Closed by mariodivece** 2017-12-12 01:21 UTC
