### ISSUE TITLE
Run with existing website

### ISSUE THREAD

**Issue by azmcnutt** [unosquare/passcore#92] opened 2017-12-11 22:54 UTC
Hi Everyone.  Is there a way to run PassCore on an existing web site by adding the application?

For instance, we have https://web.domain.org.  In IIS can I install PassCore as https://web.domain.org/password

It runs fine if we put Pass Core in as its own website, but as an application added to an existing site, we only get Loading PassCore...

Thanks,
James

**Comment by mariodivece** [comment] 2017-12-12 01:26
Duplicate of #71

**Closed by mariodivece** 2017-12-12 01:26 UTC
