### ISSUE TITLE
Works but gives error 0x80070056

### ISSUE THREAD

**Issue by bigjamee** [unosquare/passcore#8] opened 2016-02-11 21:43 UTC
This works great with one exception.  It does change the password (confirmed) but instead of a success page as expected, I get a error: Error Information: The specified network password is not correct. (Exception from HRESULT: 0x80070056)

Running on a 2012r2 server with the latest patches.

Not sure if it is checking the password twice or its not happening fast enough?

Any help would be appreciated. This is a great app!

Jamee

**Comment by justbustr** [comment] 2016-02-12 16:04
I can confirm that I'm seeing this exact same error as well, also on 2012r2. Otherwise, appears to be working well.

**Comment by schmitgreg** [comment] 2016-02-12 22:19
I get this error, too.

gns

**Comment by mariodivece** [comment] 2016-02-13 21:09
It looks like this post is describing your guys' issue.
http://stackoverflow.com/questions/9202941/system-runtime-interopservices-comexception-the-specified-network-password-is-n

I will look into this and try to find a fix

**Comment by justbustr** [comment] 2016-02-15 18:01
Thanks for looking into this issue and working on a fix. If you need any logs from us, just let me know and I can provide them to you.

**Comment by Jabettan** [comment] 2016-02-22 23:26
I can confirm this is an issue as well on the following:
Server 2012r2
Latest updates installed

It is fully functional, just kind of off-putting to users when they see red text.

**Comment by mariodivece** [comment] 2016-02-23 22:58
I'll check it out. There are several ways of changing passwords. In the next version I'll add a configuration option that allows the user to pick which password change strategy is used.

**Comment by hogsim** [comment] 2016-02-25 10:20
Hi, 
Until new version come out, is there a way to just remove this error message and get a validation that it's done? 
Thanks,

**Comment by SystemenFenB** [comment] 2016-02-25 10:49
Hi,

We are having the same bug but we are on server 2008 R2.
otherwise its working great and was easy to change to our language.
Thx

**Comment by gabrielsoltz** [comment] 2016-02-29 20:24
Same here. Thanks.

**Comment by Gregg3** [comment] 2016-03-01 19:55
PassCore was working when I tested with http.  However, now that I've applied patches to my 2012 R2 server and changed to https, I'm getting 0x80070056 like everyone else in this thread.  My 'dnvm list' shows 1.0.0-rc1-update1 as default even though 1.0.0-rc2-16551 is also in the list.  Maybe that's unrelated to the problem.  I'm willing to help test possible solutions.

**Comment by Gregg3** [comment] 2016-03-02 18:57
Solved. At least in our environment, we're not getting this error anymore.  I don't know which action actually fixed it, but we used sysinternals streams command to delete all the zone identifiers.  We also did the 'dnu restore' and 'dnvm upgrade -u' commands.  That changed our 'dnvm list' to use the 1.0.0-rc2-16551 as default. If anyone else is encountering this error, I hope these actions will help.

**Comment by Pacman1988** [comment] 2016-03-03 12:34
I tried to update with dnvm upgrade -u and dnvm list shows:

PS C:\Windows\system32> dnvm list

Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-rc1-update1 clr     x86          win
  *    1.0.0-rc2-16551   clr     x86          win             default

I have tried with iisreset and Service restarting, but I get the same error.

**Comment by Gregg3** [comment] 2016-03-03 15:16
This tool looks promising, but isn't ready to be used in a production environment. It fails to work on some browsers. In some cases, it changes the password but gives an error to the user. In other cases, it doesn't change the password at all - but just redraws the screen with all fields still containing the entered data.  Tried to enable the debugging log, but it never created any logs that I could find. Wish I had the skills to help fix some of these issues because we need a tool like this.

**Comment by justbustr** [comment] 2016-03-03 15:22
Got the same results as @Pacman1988 here.

**Comment by schmitgreg** [comment] 2016-03-03 15:34
Same as @Pacman1988, but I also ran streams to delete all the zone identifiers, and also attempted to restart individual services and the server itself, but the error is still there when users change their password.

**Comment by justbustr** [comment] 2016-03-10 19:00
Is there any timeline planned for a fix for this error message? Until it's fixed, we're not comfortable going live with PassCore in a production environment.

**Comment by NicholasBentley** [comment] 2016-03-11 01:56
Also having this issue; I wish I could help out with the actual code side of things, but I'm not well versed in a Windows environment. Thanks to @mariodivece for developing this though! It'll be awesome when this issue is gone.

**Comment by mariodivece** [comment] 2016-03-12 11:35
Guys, I just wanted to give you an update: I will try to make some time and work on these fixes on tomorrow (Sunday). You will have an additional option to specify a password change strategy. Wish me luck.

**Comment by bigjamee** [comment] 2016-03-12 11:57
Thank you and good luck!!!

**Comment by NicholasBentley** [comment] 2016-03-14 00:53
@mariodivece Thanks!

**Comment by mariodivece** [comment] 2016-03-14 03:33
I have made a pre-release version available under the Releases tab. Please test it out and let me know if it works.
The section you want to play around with is PasswordChangeOptions - See the troubleshooting section in the README.md file
All feedback is greatly appreciated :)

**Comment by NicholasBentley** [comment] 2016-03-14 04:43
@mariodivece Thanks! I'll test it out and get back to you.

**Comment by NicholasBentley** [comment] 2016-03-14 07:27
@mariodivece I've done my best and inevitably come up with some issues. After copying over the new files, the site just kept loading. Didn't even time out. I did a fresh install using the new files, same issue. I've followed the suggestions in issues 1 & 2, same issue. I then took your commit to tackle issues 7, 8, & 9 and copied only those files. Managed to get the app running, but ran into more issues. I suspect this is because there were some differences between the final commit to beta and this one.

**Comment by Pacman1988** [comment] 2016-03-14 09:35
@mariodivece I tried your Beta in a VMLab with Windows Server 2008 R2 with IIS.

I installed everything with your manual: But there is no site loading.

Then I tried in my production IIS to add a additional app and additional site. Same error, I get no site.

I deleted the new site and tested the Beta site and App on the production IIS. Then I tested the old version and I can change the passwords without a error:

![image](https://cloud.githubusercontent.com/assets/3678066/13740319/5cd4d4da-e9d0-11e5-8824-15e73237a8a8.png)

This is good, but I don't know what solved the problem...

**Comment by mariodivece** [comment] 2016-03-14 17:33
Ok, I messed up, I did not publish the file correctly. It should work now. Try the new release please.
Also please note you will most likely need to unblock the zip file if you download the file with IE. I have updated step 2 of the setup instructions to reflect this.

**Comment by gadams65** [comment] 2016-03-14 17:49
Sorry still getting the endless "Loading..." page.

**Comment by mariodivece** [comment] 2016-03-14 17:57
Ok, I have updated the release binaries. Can you try once again. If it still does not work, could you post the contents of your log file? You should see some logs in the logs folder.

**Comment by justbustr** [comment] 2016-03-14 18:15
With the latest binary, I am also unable to load the site (from the same IIS environment where PassCore 2.0.0 loaded without issue).

Here are the contents of the log:

> Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web.
> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
>    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
>    at System.Reflection.Assembly.LoadFile(String path)
>    at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
>    at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
>    at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
>    at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
>    at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
>    at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
>    at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
>    at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
>    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

**Comment by mariodivece** [comment] 2016-03-14 18:30
@justbustr Did you UNBLOCK the zip file before extracting? Please download the release zip file again, right click on properties and click the Unblock button at the bottom of the dialog.

**Comment by justbustr** [comment] 2016-03-14 18:50
@mariodivece I just did this "Unlock" and this appears to have resolved the issue I was seeing.

Thanks for the update!

**Comment by gadams65** [comment] 2016-03-14 18:52
Okay got it to come up again.  I basically deleted anything existing in my passcore folder and then copied over all the folders and files from the zip file. I also had to re-run the dnvm upgrade -u and dnu refresh commands.  I'm now getting the below message though and I'll have the check the ldap server settings.  Can this app use ldaps?  Can I use the ip address instead of hostname for my ldap server?

There was an error changing your password
Error Information: The server could not be contacted.

**Comment by mariodivece** [comment] 2016-03-14 19:02
I have not tried with an IP address but I suspect it should work. Make sure you set UseAutomaticContext to false and give it a shot by setting the LdapHostname to an IP address within double qutes. Let us know what the results are.

**Comment by gadams65** [comment] 2016-03-14 19:05
Well it was working until I restarted the site....now back to loading so I can't try the different server settings unfortunately.

**Comment by mariodivece** [comment] 2016-03-14 19:06
Try iisreset from an elevated command prompt

**Comment by mariodivece** [comment] 2016-03-14 19:07
on another note, you don't need to restart anything for changes on the appsettings.json file to take effect.

**Comment by gadams65** [comment] 2016-03-14 19:12
I was thinking I had to restart the site after changes to the appsettings.json file.  My bad. Now I'm getting a 500 Internal Server Error.  I may start from scratch.

**Comment by bigjamee** [comment] 2016-03-14 19:29
After applying updated code I had no change in the behavior.  I followed the directions to change the code to use credentials and it works.  Thank you for your efforts! #

**Comment by gadams65** [comment] 2016-03-14 20:04
I reinstalled the whole thing and can now get to the site but am now getting the following and it doesn't change the password.

There was an error changing your password
Error Information: The user name or password is incorrect.

I am putting in the correct current password so I'm wondering if it's referring to the ldap user password.  I also don't seem to accumulate log files in the log folder.

**Comment by mariodivece** [comment] 2016-03-14 20:14
Can you please redownload the beta release and try installing from scratch? I updated the release a few times and you might have gotten a faulty release.

**Comment by gadams65** [comment] 2016-03-14 20:25
I definitely have the latest version as it states it was updated 3 hours ago and I downloaded it maybe about a half hour ago.  I just reinstalled from scratch as well.

**Comment by gadams65** [comment] 2016-03-14 20:45
Success!!!!!  Not totally sure why but I'm not going to touch it now.  I changed my ldap settings back to what I had originally and it suddenly decided to work.

**Closed** 2016-03-14 21:55 UTC
Labels: bug, enhancement

**Comment by SystemenFenB** [comment] 2016-03-15 14:02
Hi,

we are still having issues with the release.
we are on server 2008 r2 with iis 7.5.
We did the unblock, we have started from scratch again.
we tried adding the credentials and setting the UseAutomaticContext to false.
But we still get the error: Error Information: The specified network password is not correct. (Exception from HRESULT: 0x80070056

any other ideas?

**Comment by mariodivece** [comment] 2016-03-15 15:30
That error message might occur when the LdapPassword setting does not contain the correct value.

**Comment by gadams65** [comment] 2016-03-15 16:20
I got this error until I got the ldap settings just right.  Make sure you have the fqdn of your ldap host.  I also put the ldap username in without any other info such as domain\ or @domain.  Only the username.

**Comment by SystemenFenB** [comment] 2016-03-16 14:16
Hi, we got it to work, with the help of 'gadams65' reply. The ldap setting is crucial and the username without the domain is as important. We got it working now!

**Comment by Gregg3** [comment] 2016-03-22 13:49
We still can't get it to work consistently.  It worked in one test on 03/14/2016 - but subsequent tests have failed with the error: "You need to provide the correct current password."  I've logged into the domain several times, so I know the password is correct.  Still getting no files in the 'logs' subdirectory. The only possible clue that I've found is Event ID 1001 from HttpPlatformHandler in the Windows Application log.  It would be nice if passcore worked with fewer dependencies. If we can figure out how to make it work, isn't it dangerous to have domain admin credentials in plain text in a web server?

**Comment by kevindiamond** [comment] 2016-07-14 18:13
I used @gadams65 advice but get:  Error Information: Exception has been thrown by the target of an invocation.

**Comment by ZioGuillo** [comment] 2016-08-19 21:39
Hi guys, i don't know if you get this error but i try it to turn off the firewall and i still received the error
anyone can help me 

There was an error changing your password
Error Information: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

**Comment by southwindz** [comment] 2016-12-05 08:53
i have same issue
There was an error changing your password
Error Information: The specified network password is not correct. (Exception from HRESULT: 0x80070056).
But my password have been changed. 
Pls give me some advise about that.
Thanks,

**Comment by ravikanchi8** [comment] 2017-01-10 12:41
Hi,

i have followed same steps given https://github.com/unosquare/passcore in this link..

pls do needful..
![passcode](https://cloud.githubusercontent.com/assets/25028785/21806591/296cf1f8-d760-11e6-8af6-e4793d405980.jpg)

**Comment by doanhp** [comment] 2017-01-10 13:31
Hello,

In step 10, it tells you how to resolve the issue. Here's the link to the instructions. It's due to IIS system.webServer/handlers section is locked. 

http://www.strathweb.com/2015/12/running-asp-net-5-website-on-iis/
