### ISSUE TITLE
Migrated AD users can't change password

### ISSUE THREAD

**Issue by szotyii** [unosquare/passcore#244] opened 2019-01-03 15:25 UTC
**PassCore Server**
- OS: Windows
- Provider: Active Directory
- Settings file (without sensitive information): 
`{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "WebSettings": {
    "EnableHttpsRedirect": true
  },
  "AppSettings": {
    // The following options for AD Provider (remove if you don't use this Provider)
    "UseAutomaticContext": true, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins"
    ], // Set the AD groups to restrict the use of PassCore
    "AllowedADGroups": ["GROUPNAME"], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "SAM", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN" (Default UPN)
    "UpdateLastPassword": true, // Set true to allow PassCore to  update the last password timestamp
    // The following options are for LDAP Provider (remove if you don't use this Provider)
    "LdapSearchBase": "ou=people,dc=example,dc=com",
    "LdapStartTls": false,
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})", // Another value: "(&(objectClass=person)(cn={Username}))"
    // General options (valid for both providers)
    "LdapHostnames": [ "" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "", // Set the password for the username
    "DefaultDomain": "" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain. This option is ONLY available with UPN.
  },
  "ClientSettings": {
    "ValidationRegex": {
      "EmailRegex": "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$",
      "UsernameRegex": "^[a-zA-Z0-9._-]{3,20}$"
    },
    "ShowPasswordMeter": true,
    "Recaptcha": {
      "SiteKey": "", // ReCAPTCHA public key: replace this! or leave empty if you don't need ReCAPTCHA
      "PrivateKey": "", // ReCAPTCHA private key: replace this! or leave empty if you don't need ReCAPTCHA
      "LanguageCode": "en"
    },
    "UseEmail": "false",
    "ApplicationTitle": "GRÁNIT-PÓLUS | Password Change",
    "ChangePasswordTitle":  "GRÁNIT-PÓLUS | Password Change",
    "ChangePasswordForm": {
      "HelpText": "If you are having trouble with this tool, please contact IT Support",
      "UsernameLabel": "Username",
      "UsernameHelpblock": "",
      "UsernameDefaultDomainHelperBlock": "",
      "CurrentPasswordLabel": "Current Password",
      "CurrentPasswordHelpblock": "",
      "NewPasswordLabel": "New Password",
      "NewPasswordHelpblock": "",
      "NewPasswordVerifyLabel": "Re-enter New Password",
      "NewPasswordVerifyHelpblock": "",
      "ChangePasswordButtonLabel": "Change Password"
    },
    "ErrorsPasswordForm": {
      "FieldRequired": "This field is required",
      "UsernamePattern": "Please enter a valid username",
      "UsernameEmailPattern": "Please enter a valid email address",
      "PasswordMatch": "Passwords do not match"
    },
    "Alerts": {
      "SuccessAlertTitle": "You have changed your password successfully.",
      "SuccessAlertBody": "Please note it may take a few hours for your new password to reach all domain controllers.",
      "ErrorPasswordChangeNotAllowed": "You are not allowed to change your password. Please contact your system administrator.",
      "ErrorInvalidCredentials": "You need to provide the correct current password.",
      "ErrorInvalidDomain": "You have supplied an invalid domain to logon to.",
      "ErrorInvalidUser": "We could not find your user account.",
      "ErrorCaptcha": "Could not verify you are not a robot",
      "ErrorFieldRequired": "Fulfill all the fields",
      "ErrorFieldMismatch": "The passwords do not match"
    }
  }
}`

**Describe the bug**
We have several AD users that we migrated from another AD forest. These migrated users can't change password through the application. If I create a new user in our forest I can change password for the new user. The corresponding log message is:
`info: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      PerformPasswordChange for user USERNAME
warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      Using AutomaticContext
warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      Failed to update password: An error occurred while enumerating the groups.  The group could not be found.`

**Desktop (please complete the following information):**
 - OS: [Windows 10 1803 Pro]
 - Browser [Chrome]
 - Version [71.0.3578.98]

**Comment by geoperez** [comment] 2019-01-21 16:04
We might include a bypass if the groups of the users are not enumerable like in your case, but I'm not really familiar with this issue in AD. Let me check the current code.

**Comment by szotyii** [comment] 2019-01-22 09:14
Hi! Thanks for your answer. I'm not sure if you have to modify anything because if I remove any group filtering from the config the error message is the same. I'll investigate this issue in AD.

**Comment by roberts4** [comment] 2019-02-07 16:20
Hi, i'm having the same issue - Failed to update password: An error occurred while enumerating the groups. The group could not be found. Tried all different combo of group and OU. Please help

**Comment by roberts4** [comment] 2019-02-07 16:20
> Hi! Thanks for your answer. I'm not sure if you have to modify anything because if I remove any group filtering from the config the error message is the same. I'll investigate this issue in AD.

Hey, did you find a answer for this? please LMK

**Comment by xquetzalcoatl** [comment] 2019-02-08 19:24
Add validation for determine if user have groups and permit to change password.

**Comment by szotyii** [comment] 2019-02-08 20:09
> Add validation for determine if user have groups and permit to change password.

Im sorry but I dont understand what you are saying. How should I do this?

**Comment by geoperez** [comment] 2019-02-08 20:10
We need to publish a new version, sorry!

**Comment by szotyii** [comment] 2019-02-08 20:11
Oh! Wonderful! Thank you!

**Comment by roberts4** [comment] 2019-02-08 20:15
Hey guys, thanks for the insight, i believe your answer will help me, due to me downloading Thycotic password reset tool and going thru the motions of setting it up. You need to give "delegate" permissions to the user account that will authenticate the service. check the installation guide here to see which permission to delegate https://thycotic.force.com/support/s/passwordresetserver

**Comment by roberts4** [comment] 2019-02-08 20:16
@szotyii  @xquetzalcoatl   Thanks guys, i'll send an update if it works but wont be able to test until tomorrow

**Comment by geoperez** [comment] 2019-02-08 20:39
Check new version 3.6.2, please.

**Comment by szotyii** [comment] 2019-02-09 00:50
It seems good now. I could change two users password which not worked before.
Thanks!

**Comment by roberts4** [comment] 2019-02-09 05:07
oh, did it work when you used version 3.6.2??

**Comment by szotyii** [comment] 2019-02-09 07:46
Yes. Only one problem. If the user not member of the AllowedADGroups still can change password. It would be great if the AllowedADGroups could be used somehow.
Thank you very much guys!

**Comment by geoperez** [comment] 2019-02-13 15:23
The issue is that AD is throwing an exception, so we cannot read the User Groups. If you can figure another way, maybe using the LDAP attribute `memberOf` let me know.

For now, I'm closing this issue.

**Closed by geoperez** 2019-02-13 15:23 UTC
