### ISSUE TITLE
can I get a redirect after a password change success

### ISSUE THREAD

**Issue by cbueche** [unosquare/passcore#48] opened 2016-10-26 09:24 UTC
Hi,

Sorry if I'm dumb and do not understand this ASP/JS stuff (I'm a Linux/Python guy), but can I get a redirection to an URL after a successful password change ?

I can't see how to do this from the documentation or the code.
Thx for your help,

Charles

**Comment by mariodivece** [comment] 2017-12-12 01:22
Duplicate of #23 Closing.

**Closed by mariodivece** 2017-12-12 01:22 UTC
